services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - ./data:/var/www/html/data
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      APP_ENV: dev
      DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: